[package]
name = "email_mask"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { tag = "v.1.0.1-beta.5", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.1.2" }